# Generated by Django 5.1.7 on 2025-03-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dt_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
