# Generated by Django 5.1.7 on 2025-04-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_dt_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
