# Generated by Django 5.1.7 on 2025-06-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_evaluation_fk_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dt_init',
            field=models.DateField(null=True),
        ),
    ]
