# Generated by Django 5.1.7 on 2025-06-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_dt_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time_interval',
            field=models.IntegerField(null=True),
        ),
    ]
