# Generated by Django 5.1.7 on 2025-03-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('G', 'Gestor'), ('U', 'User')], max_length=1),
        ),
    ]
