# Generated by Django 5.1.7 on 2025-03-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_user_clients'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
