# Generated by Django 5.1.7 on 2025-03-15 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clients',
            field=models.ManyToManyField(blank=True, null=True, related_name='managed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
