# Generated by Django 5.1.7 on 2025-03-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_type'),
        ('milestones', '0001_initial'),
        ('stages', '0002_stage_comments_stage_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='comments',
            field=models.ManyToManyField(related_name='milestone_comments', to='files.file'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='files',
            field=models.ManyToManyField(related_name='milestone_files', to='files.file'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='stages',
            field=models.ManyToManyField(related_name='milestone_stages', to='stages.stage'),
        ),
    ]
