# Generated by Django 5.1.7 on 2025-03-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0002_milestone_comments_milestone_files_milestone_stages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='is_final',
        ),
    ]
