# Generated by Django 5.1.7 on 2025-04-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0003_remove_milestone_is_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
