# Generated by Django 5.1.7 on 2025-04-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0004_milestone_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
