# Generated by Django 5.1.7 on 2025-04-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0005_milestone_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='stages',
        ),
    ]
