# Generated by Django 5.1.7 on 2025-03-07 13:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('dt_creation', models.DateField()),
                ('is_final', models.BooleanField(default=False)),
                ('stages', models.ManyToManyField(related_name='substages', to='stages.stage')),
            ],
        ),
    ]
