# Generated by Django 5.1.7 on 2025-03-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_type'),
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='comments',
            field=models.ManyToManyField(related_name='stage_comments', to='files.file'),
        ),
        migrations.AddField(
            model_name='stage',
            name='files',
            field=models.ManyToManyField(related_name='stage_files', to='files.file'),
        ),
    ]
