# Generated by Django 5.1.7 on 2025-03-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_stage_comments_stage_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='is_final',
        ),
    ]
