# Generated by Django 5.1.7 on 2025-03-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_remove_stage_is_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='dt_creation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
