# Generated by Django 5.1.7 on 2025-03-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_alter_stage_dt_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='dt_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
