# Generated by Django 5.1.7 on 2025-04-29 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0006_remove_milestone_stages'),
        ('stages', '0005_alter_stage_dt_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='stages',
        ),
        migrations.AddField(
            model_name='stage',
            name='fk_milestone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestone_stage', to='milestones.milestone'),
        ),
        migrations.AddField(
            model_name='stage',
            name='fk_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substages', to='stages.stage'),
        ),
    ]
