# Generated by Django 5.1.7 on 2025-03-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('img', 'img'), ('pdf', 'pdf'), ('csv', 'csv'), ('excel', 'excel')], max_length=5, null=True),
        ),
    ]
