# Generated by Django 5.1.7 on 2025-03-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('img', 'Imagem'), ('pdf', 'PDF'), ('csv', 'CSV'), ('excel', 'Excel'), ('docx', 'Word (DOCX)'), ('txt', 'Texto (TXT)'), ('pptx', 'PowerPoint (PPTX)'), ('zip', 'Arquivo ZIP')], max_length=5, null=True),
        ),
    ]
