# Generated by Django 5.1.7 on 2025-03-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
