# Generated by Django 5.1.7 on 2025-03-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
