# Generated by Django 5.1.7 on 2025-04-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('image', 'Imagem'), ('pdf', 'PDF'), ('csv', 'CSV'), ('excel', 'Excel'), ('docx', 'Word (DOCX)'), ('txt', 'Texto (TXT)'), ('pptx', 'PowerPoint (PPTX)'), ('zip', 'Arquivo ZIP')], max_length=5, null=True),
        ),
    ]
