# Generated by Django 5.1.7 on 2025-05-08 10:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_alter_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocr',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('docName', models.CharField(max_length=244)),
                ('ocrDesorganizado', models.TextField()),
                ('ocrOrganizado', models.TextField()),
            ],
        ),
    ]
