# Generated by Django 5.1.7 on 2025-05-16 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_ocr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ocr',
        ),
    ]
